### PR TITLE
368 improve exported metrics for usage in grafana dashboards

### PR DESCRIPTION
**Pull request by gianfra-t**
A display label is added of the form `{collateral}_{wrapped}`

Where both collateral and wrapped are formatted for display the following way:
```
XCM = "XCM(value)",
StellarNative = "XLM"
Native = "Native"
Stellar::AlphaNum4 {code, ..} | AlphaNum12 {code, ..} = "code"
CurrencyId::ZenlinkLPToken(token1_id, token1_type, token2_id, token2_type) = "LP_{}_{}_{}_{}", token1_id, token1_type, token2_id, token2_type)
```

Also appends status or type of the corresponding metric so that display name is formatted as 
```
"{collateral}_{wrapped} - {status/type}"
```

### CODE REVIEW

**Review by ebma — APPROVED** [review]
Looks good 👍 the formatting/indentation is off though. Please run `rustfmt` and consider running [this](https://github.com/pendulum-chain/spacewalk/blob/368-improve-exported-metrics-for-usage-in-grafana-dashboards/.maintain/add-precommit-hook.sh) script to install a pre-commit hook for Spacewalk that runs rustfmt on each commit. 

Ready to merge once formatting is fixed and CI passed

**Comment by gianfra-t** [comment]
Yes! it happens to me quite often that very simple clippy and format changes are off. I will install the pre-commit hook.

**Comment by gianfra-t** [comment]
@ebma any idea why the test might be failing? When looking at the errors,`op_no_destination` and `op_no_destination` seem to me like the Stellar test accounts might have an issue.

**Comment by ebma** [comment]
Right, I think it was related to the Stellar testnet reset but I set up the accounts again and it restarted the CI job so let's see.

**Comment by ebma** [comment]
I had another look and we need #470 to fix the tests. Once that PR is merged we can rebase this one and it should be fixed 🤞

**Pull request merged**
