### PR TITLE
Re-run benchmarks for custom pallets

### LINKED ISSUE #496: Run benchmarks for all custom pallets
## Context

The [PR](https://github.com/pendulum-chain/spacewalk/pull/415) related to `pooled-rewards` pallet introduced benchmarks changes and that requires them to be re-run so that weights are updated.
Currently there are benchmarks which were modified but the default_weights.rs file remained inconsistent e.g. `fee` pallet ([benchmarking.rs](https://github.com/pendulum-chain/spacewalk/blob/bda384bcc6db3da88198c714851a261dcdea1063/pallets/fee/src/benchmarking.rs), [default_weights.rs](https://github.com/pendulum-chain/spacewalk/blob/bda384bcc6db3da88198c714851a261dcdea1063/pallets/fee/src/default_weights.rs))

## Requirement

Re-run benchmarks for all custom pallets so that weights are updated.

### PR DESCRIPTION
**Pull request by bogdanS98**
Closes #496.

~Still WIP as running benchmarks for `vault-registry` pallet results in panic:~

~at: spacewalk/pallets/vault-registry/src/benchmarking.rs:154
`Error: Input("Error executing and verifying runtime benchmark: Runtime panicked: called Result::unwrap() on an Err value: Module(ModuleError { index: 21, error: [1, 0, 0, 0], message: Some(\"ExceedingVaultLimit\") })") Evicting failed runtime instance error=Runtime panicked: called Result::unwrap() on an Err value: Module(ModuleError { index: 21, error: [1, 0, 0, 0], message: Some("ExceedingVaultLimit") })`~

Fixed `vault-registry` benchmarks panic by setting the issue amount from `10000` to `5000` [here](https://github.com/pendulum-chain/spacewalk/pull/497/files#diff-6cfd9e0cee5ea993beaaec62ecd57292992b7a1fc574ef2ac50d66d2ed3faa05R153).

### CODE REVIEW

**Comment by ebma** [comment]
What's the error in the panic?

**Comment by bogdanS98** [comment]
> What's the error in the panic?

`Error: Input("Error executing and verifying runtime benchmark: Runtime panicked: called `Result::unwrap()` on an `Err` value: Module(ModuleError { index: 21, error: [1, 0, 0, 0], message: Some(\"ExceedingVaultLimit\") })")
Evicting failed runtime instance error=Runtime panicked: called `Result::unwrap()` on an `Err` value: Module(ModuleError { index: 21, error: [1, 0, 0, 0], message: Some("ExceedingVaultLimit") })`

**Review by ebma — APPROVED** [review]
Looks good to me 👍 please only merge when CI passes though. Or if it fails because of a shaky test we can also think about merging but there at least shouldn't be any build issues.

**Comment by b-yap** [comment]
I cancelled the CI since there's another one running. I'll rerun it afterwards.

**Pull request merged**
