### PR TITLE
Dev/38 resolve parity util mem compile error

### PR DESCRIPTION
**Pull request by ashneverdawn**

### CODE REVIEW

**Comment by ebma** [comment]
What exactly fixed this error? I noticed that the vault compilation fails for the current main branch now so we would need it on the main branch as well.

**Comment by gonzamontiel** [comment]
HJey @ebma , It was bumping the polkadot version to v0.9.18, and it was actually also merged to the main branch in https://github.com/pendulum-chain/spacewalk/pull/60

Could be _that_ the cause of the problem in the main branch?

**Comment by ebma** [comment]
Yes, it seems like #60 introduced this error on the main branch. But I thought this PR contains a fix for it? I'm a bit confused

**Comment by gonzamontiel** [comment]
@ebma can you create an issue on main describing the compilation errors?

**Comment by ebma** [comment]
I now created an issue ticket (#69) for this.

**Pull request merged**
