### PR TITLE
add #[require_transactional] to all functions that require transactional

### PR DESCRIPTION
**Pull request by RustNinja**
add #[require_transactional] to all functions that require transactional

### CODE REVIEW

**Review by ebma — CHANGES_REQUESTED** [review]
Did you test if this works with all tests and benchmarks. Because I remember that after you added the `require_transactional` to some function in the stellar-relay pallet (which made sense) the benchmarks for it did not work anymore because it is calling this internal helper function but the benchmark extrinsic is not a `transaction` itself somehow. 
I didn't look into that more deeply 2 weeks ago but just removed it again because there was not so much time but maybe you can look into it now? Just run some benchmark for a pallet by following the steps in the respective README and I guess you will see the issue I'm talking about

**Comment by cr4pt0** [comment]
@ebma 
There are still errors in tests because of `require_transactional`.

**Comment by ebma** [comment]
Can you fix them then or is it too complicated @cr4pt0?

**Comment by erasmus** [comment]
@RustNinja what should we do with this PR here? 🤔

**Comment by erasmus** [comment]
@RustNinja what should we do with this PR here? 🤔

**Comment by RustNinja** [comment]
> Can you fix them then or is it too complicated @RustNinja ?

let's close it. because in other case we need rewrite tests. and there is no need to use require transaction for our functions because the is no stage updates and then error panic.
It is just safety that in future we will not write any code rust will update storage even when error dispatched from extrinsic.

**Pull request closed without merging**
